version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: node index.js
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    networks:
      - node-network
  nginx:
    build:
      context: nginx
    image: nginx:1.15.0-alpine
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
networks:
  node-network:
    driver: bridge
